Accounts/urls.py
from django.urls import path, re_path
from . import views as account_views
from Projects import views as project_views
from Miscellaneous import views as MiscViews

app_name = "Accounts"

urlpatterns = [
    # Registeration URLs:
    # path('signup/', account_views.SignupView.as_view(), name='signup'),
    # path('signupform/', account_views.signup_form, name='signupform'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        account_views.activate, name='activate'),

    # Login URLs:
    # path('login/', account_views.LoginFormDef, name='login'),
    # path('logout/', account_views.LogoutView, name='logout'),

    # Dashboard URLs:
    # path('dashboard/', account_views.DashboardView.as_view(), name='dashboard'),
    path('about/', account_views.ProfileAboutView.as_view(), name='profile_about'),
    path('pricing/', account_views.PricingView.as_view(), name='pricing'),

    # Profile URLs:
    path('account_settings/', account_views.AccountSettingsView.as_view(), name='account_settings'),
    path('profile_change/', account_views.profile_change_form, name='profile_change'),
    path('account_info_change/', account_views.account_info_change_form, name='account_info_change'),
    path('bank_details_change/', account_views.bank_details_change_form, name = 'bank_details_change'),

    # Feed URLs:
    path('subscribe/<str:viewed_user>', account_views.subscribe, name='subscribe'),
    path('unsubscribe/<str:viewed_user>', account_views.unsubscribe, name='unsubscribe'),

    # path('user_internship/<str:username>/', account_views.user_internship_form, name='user_internship_form'),
    # path('user_collaboration/<str:username>/', account_views.user_collaboration_form, name='user_collaboration_form'),



]

Projects/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Projects import views as project_views
from django_filters.views import FilterView
from . import models
from django.conf.urls import handler404, handler500, handler403
app_name = "Projects"

handler404 = 'Projects.views.handler404'
handler500 = 'Projects.views.handler500'

urlpatterns = [
    # path('details/<int:project_id>', project_views.ProjectDetailView,  name='project_details'),
    path('add_project/', project_views.AddProjectView.as_view(), name='add_project'),
    path('add_project_form/', project_views.add_project_form, name='add_project_form'),
    path('recommendation_form/<str:slug>', project_views.recommendation_form, name='recommendation_form'),
    path('recommendation_view/<str:slug>', project_views.view_recommendations, name='recommendation_view'),
    path('acceptrecom/<int:recom_id>', project_views.acceptrecom, name="acceptrecom"),
    path('rejectrecom/<int:recom_id>', project_views.rejectrecom, name="rejectrecom"),
    path('challenge_grants/', project_views.ChallengeGrants.as_view(), name='challenge_grants'),
    # path('delete_view/', project_views.DeleteProjectView.as_view(), name='delete_view'),
    path('delete_project/<str:slug>/', project_views.delete_project, name='delete_project'),
    path('edit_project/<str:slug>', project_views.EditView.as_view(), name='edit_project'),
    path('edit_project_submit/<str:slug>', project_views.edit_project_form, name='edit_project_form'),
    path('deadline_extension/<str:slug>', project_views.deadline_extension, name='deadline_extension'),
    path('dead_req_det/<str:slug>', project_views.dead_request_details, name='dead_req_det'),
    path('accept_dead/<str:slug>', project_views.accept_dead, name='accept_dead'),
    path('reject_dead/<str:slug>', project_views.reject_dead, name='reject_dead'),
    #path('project_list/', project_views.ProjectListView, name='projectlistview'),
    path('add_book/<str:slug>', project_views.add_book, name='add_book'),
    path('rem_book.<str:slug>', project_views.rem_book, name='rem_book'),

    path('mentorship_form/<str:slug>', project_views.mentor_form, name='mentorship_form'),
    path('mentorship_view/<str:slug>', project_views.view_mentorships, name='mentorship_view'),
    path('acceptmentor/<int:mentor_id>', project_views.acceptmentor, name="acceptmentor"),
    path('rejectmentor/<int:mentor_id>', project_views.rejectmentor, name="rejectmentor"),

    path('internship_form/<str:slug>', project_views.intern_form, name='internship_form'),
    path('internship_view/<str:slug>', project_views.view_internships, name='internship_view'),
    path('acceptintern/<int:intern_id>', project_views.acceptintern, name="acceptintern"),
    path('rejectintern/<int:intern_id>', project_views.rejectintern, name="rejectintern"),

    path('collaborator_form/<str:slug>', project_views.colab_form, name='collaborator_form'),
    path('internship_view/<str:slug>', project_views.view_collaborations, name='collaborator_view'),
    path('acceptintern/<int:colab_id>', project_views.acceptcolab, name="acceptcolab"),
    path('rejectintern/<int:colab_id>', project_views.rejectcolab, name="rejectcolab"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdfund/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path

from Accounts import views as account_views
from Projects import views as project_views
from Miscellaneous import views as MiscViews




urlpatterns = [
    path('admin/', admin.site.urls),
#  path('', account_views.LandingPageView.as_view(), name='home'),
    path('', account_views.DashboardView.as_view(), name='home'),
    path('user_accounts/', include('Accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('transactions/', include('transactions.urls')),
    path('projects/', include('Projects.urls')),
    path('<str:username>/<str:slug>/', project_views.ProjectDetailView, name='project_details'),
    path('dashboard/', account_views.DashboardView.as_view(), name='dashboard'),
    path('login/', account_views.LoginFormDef, name='login'),
    path('logout/', account_views.LogoutView, name='logout'),

    path('signup/', account_views.SignupView.as_view(), name='signup'),
    path('signupform/', account_views.signup_form, name='signupform'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            account_views.activate, name='activate'),
    path('browse/', project_views.browse_projects, name='browse_projects'),
    path('misc/', include('Miscellaneous.urls')),

    path('<str:username>/', account_views.UserProfileView, name='user_profile'),


]

Projects/views.py
import datetime
from re import split

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.http import HttpResponseRedirect
from Accounts import forms
from Projects import forms as project_forms
from Accounts.models import CustomUser, History
from Projects.forms import RecommendationForm, EditProjectForm
from Projects.models import ProjectDetails, References, BankInformation, ProjectTags, Collaborators, Contributors, \
    Recommendations, Bookmarks, Mentors, Interns
from django.contrib.auth import get_user_model
from Projects.models import References
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from pyshorteners import Shortener
from django.views.generic import ListView
from rest_framework.viewsets import generics
from . import serializers
from . import filters
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter, SearchFilter


API_Key = 'AIzaSyDzcS4JR1ZfMxzP43o-syrR9-JHlxpl3As'


# from Projects.forms import ProjectForm

# Create your views here.
from django.views.generic import TemplateView


User = get_user_model()


# class ProjectListView(generics.ListAPIView):
#     serializer_class = serializers.ProjectSerializer
#     queryset = ProjectDetails.objects.all()
#     filter_backends = (DjangoFilterBackend, OrderingFilter, SearchFilter)
#     filter_fields = ('title','description',)
#     # ordering_fields = ('',)
#     search_fields = ('title', 'description',)


def handler404(request, exception):
    return HttpResponseRedirect('/user_accounts/login/')

def handler500(request):
    return HttpResponseRedirect('user_accounts/login/')


def ProjectDetailView(request, username, slug):

    url =  "oversight.in{}".format(request.get_full_path())

    try:
        current_project = ProjectDetails.objects.get(project_slug=slug)
    except Exception as e:
        return HttpResponse("Such a Project Does Not Exist")
    user = CustomUser.objects.get(username__exact=current_project.user.username)
    try:
        Cont = Contributors.objects.filter(project_id=current_project.project_id)[:10]
    except Exception as e:
        pass

    try:
        Collabs = Collaborators.objects.filter(project_id=current_project.project_id).filter(approved=True)
    except Exception as e:
        pass

    try:
        Recoms = Recommendations.objects.filter(approved=True).filter(project_id=current_project.project_id).order_by('date_written')
    except Exception as e:
        pass
    try:
        viewing_user = CustomUser.objects.get(username=request.user.username)
        viewing_user_bookmarks = Bookmarks.objects.filter(user=viewing_user)

    except Exception as e:
        viewing_user = None
        viewing_user_bookmarks = None

    if viewing_user_bookmarks is not None:
        if current_project.project_id in viewing_user_bookmarks.values_list('project_id__project_id', flat=True):
            booked = True
        else:
            booked = False
    else:
        booked = None
    project_bookmarks = Bookmarks.objects.filter(project_id__project_slug=current_project.project_slug)
    Ints = Interns.objects.filter(project_id=current_project.project_id).filter(approved=True)

    if user.username == username:
        return render(request, 'Projects/project_details.html', {'short_url': url, 'user':user, 'Project': current_project, 'Recommendations':Recoms, 'Collaborators':Collabs, 'viewing_user':viewing_user, 'booked':booked, 'project_bookmarks': project_bookmarks, 'Interns':Ints})
    else:
        return HttpResponse("Unauthorized")


class AddProjectView(LoginRequiredMixin, TemplateView):

    login_url = '/login/'
    redirect_field_name = None

    template_name = 'Projects/addproject.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['colablist'] = CustomUser.objects.exclude(username=self.request.user.username)
        context['user'] = CustomUser.objects.get(username=self.request.user.username)
        return context


@login_required(login_url = '/login/', redirect_field_name=None)
def add_project_form(request):
    if request.method == 'POST':
        form = project_forms.AddProjectForm(request.POST)
        print("form received")
        print(form.errors)
        if form.is_valid():
            sluglist = ProjectDetails.objects.filter(user=request.user)
            sluglist = sluglist.values_list('project_slug', flat=True)
            if form.cleaned_data['project_slug'] not in sluglist:
                print("Form Cleaned")
                project = ProjectDetails()
                project.user = CustomUser.objects.get(username=request.user.username)
                project.title = form.cleaned_data['title']
                project.project_slug = form.cleaned_data['project_slug'].lower()

                project.abstract = form.cleaned_data['abstract']
                project.description = form.cleaned_data['description']
                project.significance = form.cleaned_data['significance']
                project.additional_details = form.cleaned_data['additional_details']
                project.target_amount = form.cleaned_data['target_amount']
                # s = "{}-{}-{}".format(form.cleaned_data['deadline_year'], form.cleaned_data['deadline_month'], form.cleaned_data['deadline_day'])
                # deadline = datetime.datetime.strptime(s,"%Y-%m-%d").date()
                # project.deadline = deadline
                project.codebase = form.cleaned_data['codebase']
                project.dataset = form.cleaned_data['dataset']
                project.intellectual_property = form.cleaned_data['intellectual_property']
                project.reference1 = form.cleaned_data['reference1']
                project.reference2 = form.cleaned_data['reference2']
                project.reference3 = form.cleaned_data['reference3']
                project.affiliation = form.cleaned_data['affiliation']
                if form.cleaned_data['accept_collaborators']:
                    project.accept_collaborators = form.cleaned_data['accept_collaborators']
                else:
                    project.accept_collaborators = 'off'

                if form.cleaned_data['accept_interns']:
                    project.accept_interns = form.cleaned_data['accept_interns']
                else:
                    project.accept_interns = 'off'

                if form.cleaned_data['accept_mentors']:
                    project.accept_mentors = form.cleaned_data['accept_mentors']
                else:
                    project.accept_mentors = 'off'
                project.save()
                tag_list = form.cleaned_data['tags'].split(',')
                for tag in tag_list:
                    proj_tag = ProjectTags()
                    proj_tag.project_id = ProjectDetails.objects.get(project_id=project.project_id)
                    proj_tag.tag = tag
                    proj_tag.save()

                colab_list = form.cleaned_data['collaborators'].split(',')

                for col in colab_list:
                    colab = Collaborators()
                    print(col)
                    colab.project_id = ProjectDetails.objects.get(project_id=project.project_id)
                    try:
                        colab.requesting_user = CustomUser.objects.get(username=col)
                    except Exception as e:
                        continue
                    colab.approved = True
                    colab.save()
                hist = History()
                hist.project_id = project
                hist.user = request.user
                hist.type_of_action = "Creation"
                hist.save()
                return redirect('project_details', username=request.user.username, slug=project.project_slug )
            else:
                messages.error(request, "This slug is already in use for one of your projects")
                return render(request, 'Projects/addproject.html', {'errors': form.errors,
                                                                    'colablist': CustomUser.objects.all().exclude(
                                                                        username=request.user.username),
                                                                    'user': CustomUser.objects.get(
                                                                        username=request.user.username)})

        else:
            return render(request, 'Projects/addproject.html', {'errors':form.errors, 'colablist': CustomUser.objects.all().exclude(username=request.user.username), 'user': CustomUser.objects.get(username=request.user.username)})

@login_required(login_url='/login/', redirect_field_name=None)
def recommendation_form(request, slug):
    if request.method == 'POST' and request.user != ProjectDetails.objects.get(project_slug=slug).user:
        form = RecommendationForm(request.POST)
        proj = ProjectDetails.objects.get(project_slug=slug)
        if form.is_valid():
            reco = Recommendations()
            reco.project_id = ProjectDetails.objects.get(project_slug=slug)
            reco.writing_user = CustomUser.objects.get(username=request.user.username)
            reco.Text = form.cleaned_data['Text']
            reco.save()

            mail_subject = 'A New Recommendation for {}'.format(reco.project_id.title)
            body = render_to_string('Projects/emails/recom_mail.html', {
                'user': request.user.username,
                'Project': reco.project_id,
                'recom': reco,
            })

templates/Projects/addproject-old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Project</title>
</head>
<body>
{% for error in errors %}
    <p>{{ error }}</p>
{% endfor %}
<form method="post" action="{% url 'Projects:add_project_form' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <p><input type="text" name="title" placeholder="Project Title"></p>
    <p><input type="text" name="abstract" placeholder="Abstract"></p>
    <p><input type="text" name="description" placeholder="Description"></p>
    <p><input type="text" name="significance" placeholder="Significance"></p>
    <p><input type="text" name="additional_details" placeholder="Additional Details"></p>
    <p><input type="file" name="public_proposal" placeholder="Public Proposal"></p>
    <p><input type="text" name="target_amount" placeholder="Target Amount"></p>
    <p><input type="text" name="reference_text" placeholder="Reference Text"></p>
    <p><input type="text" name="link_url" placeholder="Reference Links"></p>
    <p><input type="text" name="bank_ifsc" placeholder="Bank IFSC"></p>
    <p><input type="text" name="account_no" placeholder="Account Number"> </p>
    <p><input type="text" name="beneficiary_name" placeholder="Beneficiary Name"></p>
    <p><input type="text" name="affiliations" placeholder="Affiliations with individuals/institutions"></p>
    <p><input type="text" name="tags" placeholder="Tags"></p>
    <p><input type="file" name="image" placeholder="Project Image"></p>
    <button type="submit" value="Create Project"></button>



</form>
  {% include "footer-internal.html" %}

</body>
</html>

templates/Projects/challenge_grants.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Challenge Grants</title>
</head>
<body>

</body>
</html>

templates/Projects/colab_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submitted Collaboration Requests</title>
</head>
<body>
<h2>These are the submitted mentorship requests for {{ project.title }}</h2>
{% for colabs in collaborators %}
<h5>Submitted By:</h5>
<p>Username:{{ colabs.requesting_user.username }}</p>
<p>First Name:{{ colabs.requesting_user.first_name }}   Last Name:{{ colabs.requesting_user.last_name }} </p>
<p>Relevant Qualification:{{ recom.relevant_qualification }} </p>
<p>LinkedIn Profile:<a href="{{ recom.LinkedIn_profile }}">{{ recom.LinkedIn_profile }}</a> </p>
<h5>Body:</h5>
<p>{{ colabs.body }}</p>
    <br><br><br>
    <a href="{% url 'Projects:acceptcolab' colab_id=colabs.collaborator_id %}">Accept</a>
    <a href="{% url 'Projects:rejectcolab' colab_id=colabs.collaborator_id %}">Reject</a>
{% endfor %}
</body>
</html>

templates/Projects/dead_request_details.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deadline Request Details</title>
</head>
<body>
<h1> User {{ user.username }} is requesting a deadline extension for the project {{ Project.title }} </h1>
<br><br><br>
<h3>User Details</h3>
<p>Username: {{ user.username }}</p>
<p>First Name: {{ user.first_name }}</p>
<p>Last Name{{ user.last_name }}</p>
<p>Email ID: {{ user.email }}</p>
<p>Institution: {{ user.profile.institution }}</p>
<p>Bio: {{ user.profile.bio }}</p>
<p>Website: {{ user.profile.website }}</p>
<p>Phone Number: {{ user.profile.phone_no }}</p>
<br><br>
<h3>Project Details</h3>
<p>Title: {{ Project.title }}</p>
<p>Slug: {{ Project.project_slug }}</p>
<p>Abstract: {{ Project.abstract }}</p>
<p>Description: {{ Project.description }}</p>
<p>Significance: {{ Project.significance }}</p>
<p>Additional Details: {{ Project.additional_details }}</p>
<p>Affiliations: {{ Project.affiliations }}</p>
<p>Target Amount: {{ Project.target_amount }}</p>
<p>Current Earnings: {{ Project.balance_amount }}</p>
<p>Completion Percentage: {{ Project.completion_percentage }}</p>
<p>Reference 1: {{ Project.reference1 }}</p>
<p>Reference 2: {{ Project.reference2 }}</p>
<p>Reference 3: {{ Project.reference3 }}</p>
<p>Codebase: {{ Project.codebase }}</p>
<p>Dataset: {{ Project.dataset }}</p>
<p>Intellectual Property: {{ Project.intellectual_property }}</p>
<p>Accepting Collaborators: {{ Project.accept_collaborators }}</p>
<p>Accepting Interns: {{ Project.accept_interns }}</p>
<p>Accepting Mentors: {{ Project.accept_mentors }}</p>
<p>Applied Fees: {{ Project.fees }}</p>
<p>Current Deadline: {{ Project.deadline }}</p>
<br><br>
<h3>User History</h3>
{% for event in user_hist %}
<p>{{ event.time_of_action }}: {{ event.type_of_action }}</p>
{% endfor %}
<br><br>
<h3>Project History</h3>
{% for event in proj_hist %}
    <p>{{ event.time_of_action }}: {{ event.type_of_action }}</p>
{% endfor %}
<br><br><br><br><br><br><br>
<h2>New Requested Deadline: {{ new_dead }}</h2>
<a href="{% url 'Projects:accept_dead' slug=Project.project_slug %}">Accept Request</a>
<a href="{% url 'Projects:reject_dead' slug=Project.project_slug %}">Reject Request</a>
</body>
</html>

templates/Projects/intern_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submitted Internship Request</title>
</head>
<body>
<h2>These are the submitted mentorship requests for {{ project.title }}</h2>
{% for interns in internships %}
<h5>Submitted By:</h5>
<p>Username:{{ interns.requesting_user.username }}</p>
<p>First Name:{{ interns.requesting_user.first_name }}   Last Name:{{ interns.requesting_user.last_name }} </p>
{#<p>Relevant Qualification:{{ recom.relevant_qualification }} </p>#}
{#<p>LinkedIn Profile:<a href="{{ recom.LinkedIn_profile }}">{{ recom.LinkedIn_profile }}</a> </p>#}
<h5>Body:</h5>
<p>{{ interns.body }}</p>
    <br><br><br>
    <a href="{% url 'Projects:acceptintern' intern_id=interns.intern_id %}">Accept</a>
    <a href="{% url 'Projects:rejectintern' intern_id=interns.intern_id %}">Reject</a>
{% endfor %}
</body>
</html>

templates/Projects/mentor_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submitted Mentorship Request</title>
</head>
<body>
<h2>These are the submitted mentorship requests for {{ project.title }}</h2>
{% for mentors in mentorships %}
<h5>Submitted By:</h5>
<p>Username:{{ mentors.requesting_user.username }}</p>
<p>First Name:{{ mentors.requesting_user.first_name }}   Last Name:{{ mentors.requesting_user.last_name }} </p>
<p>Relevant Qualification:{{ recom.relevant_qualification }} </p>
<p>LinkedIn Profile:<a href="{{ recom.LinkedIn_profile }}">{{ recom.LinkedIn_profile }}</a> </p>
<h5>Body:</h5>
<p>{{ mentors.body }}</p>
    <br><br><br>
    <a href="{% url 'Projects:acceptmentor' mentor_id=mentors.mentor_id %}">Accept</a>
    <a href="{% url 'Projects:rejectmentor' mentor_id=mentors.mentor_id %}">Reject</a>
{% endfor %}
</body>
</html>

templates/Projects/project_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deleting Projects</title>
</head>
<body>
<h1>You Are Deleting A Project</h1>
<h3>Please Enter the Slug of the project you are deleting below:</h3>
<form method="post" action="{% url 'Projects:delete_project' slug=slug %}">
    <input type="text" name="">


</form>
</body>
</html>

templates/Projects/recom_form.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recommendation</title>
</head>
<body>
<h2>Please Fill The Following Form For The Project:{{ project.title }}</h2>
{% for error in errors %}
<p>{{ error }}</p>
{% endfor %}

<form method="post" action="{% url 'Projects:recommendation_form' project.project_slug %}">
    {% csrf_token %}
    <input type="url" name="LinkedIn_profile" placeholder="Your LinkedIn Profile" required>
    <input type="text" name="relevant_qualification" placeholder="Your Most Relevant Qualification / Position" required>
    <input type="text" name="Text" placeholder="Write The Body Of Your Recommendation Here" required>
    <button type="submit">Recommend</button>
</form>
</body>
</html>

templates/Projects/recom_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submitted Recommendations</title>
</head>
<body>
<h2>These are the submitted recommendations for {{ project.title }}</h2>
{% for recom in recommendations %}
<h5>Submitted By:</h5>
<p>Username:{{ recom.writing_user.username }}</p>
<p>First Name:{{ recom.writing_user.first_name }}   Last Name:{{ recom.writing_user.last_name }} </p>
<p>Relevant Qualification:{{ recom.relevant_qualification }} </p>
<p>LinkedIn Profile:<a href="{{ recom.LinkedIn_profile }}">{{ recom.LinkedIn_profile }}</a> </p>
<h5>Body:</h5>
<p>{{ recom.Text }}</p>
    <br><br><br>
    <a href="{% url 'Projects:acceptrecom' recom_id=recom.recom_id %}">Accept</a>
    <a href="{% url 'Projects:rejectrecom' recom_id=recom.recom_id %}">Reject</a>
{% endfor %}
</body>
</html>