Accounts/urls.py
from django.urls import path, re_path
from . import views as account_views
from Projects import views as project_views
from Miscellaneous import views as MiscViews

app_name = "Accounts"

urlpatterns = [
    # Registeration URLs:
    # path('signup/', account_views.SignupView.as_view(), name='signup'),
    # path('signupform/', account_views.signup_form, name='signupform'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        account_views.activate, name='activate'),

    # Login URLs:
    # path('login/', account_views.LoginFormDef, name='login'),
    # path('logout/', account_views.LogoutView, name='logout'),

    # Dashboard URLs:
    # path('dashboard/', account_views.DashboardView.as_view(), name='dashboard'),
    path('about/', account_views.ProfileAboutView.as_view(), name='profile_about'),
    path('pricing/', account_views.PricingView.as_view(), name='pricing'),

    # Profile URLs:
    path('account_settings/', account_views.AccountSettingsView.as_view(), name='account_settings'),
    path('profile_change/', account_views.profile_change_form, name='profile_change'),
    path('account_info_change/', account_views.account_info_change_form, name='account_info_change'),
    path('bank_details_change/', account_views.bank_details_change_form, name = 'bank_details_change'),

    # Feed URLs:
    path('subscribe/<str:viewed_user>', account_views.subscribe, name='subscribe'),
    path('unsubscribe/<str:viewed_user>', account_views.unsubscribe, name='unsubscribe'),

    # path('user_internship/<str:username>/', account_views.user_internship_form, name='user_internship_form'),
    # path('user_collaboration/<str:username>/', account_views.user_collaboration_form, name='user_collaboration_form'),



]

Projects/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Projects import views as project_views
from django_filters.views import FilterView
from . import models
from django.conf.urls import handler404, handler500, handler403
app_name = "Projects"

handler404 = 'Projects.views.handler404'
handler500 = 'Projects.views.handler500'

urlpatterns = [
    # path('details/<int:project_id>', project_views.ProjectDetailView,  name='project_details'),
    path('add_project/', project_views.AddProjectView.as_view(), name='add_project'),
    path('add_project_form/', project_views.add_project_form, name='add_project_form'),
    path('recommendation_form/<str:slug>', project_views.recommendation_form, name='recommendation_form'),
    path('recommendation_view/<str:slug>', project_views.view_recommendations, name='recommendation_view'),
    path('acceptrecom/<int:recom_id>', project_views.acceptrecom, name="acceptrecom"),
    path('rejectrecom/<int:recom_id>', project_views.rejectrecom, name="rejectrecom"),
    path('challenge_grants/', project_views.ChallengeGrants.as_view(), name='challenge_grants'),
    # path('delete_view/', project_views.DeleteProjectView.as_view(), name='delete_view'),
    path('delete_project/<str:slug>/', project_views.delete_project, name='delete_project'),
    path('edit_project/<str:slug>', project_views.EditView.as_view(), name='edit_project'),
    path('edit_project_submit/<str:slug>', project_views.edit_project_form, name='edit_project_form'),
    path('deadline_extension/<str:slug>', project_views.deadline_extension, name='deadline_extension'),
    path('dead_req_det/<str:slug>', project_views.dead_request_details, name='dead_req_det'),
    path('accept_dead/<str:slug>', project_views.accept_dead, name='accept_dead'),
    path('reject_dead/<str:slug>', project_views.reject_dead, name='reject_dead'),
    #path('project_list/', project_views.ProjectListView, name='projectlistview'),
    path('add_book/<str:slug>', project_views.add_book, name='add_book'),
    path('rem_book.<str:slug>', project_views.rem_book, name='rem_book'),

    path('mentorship_form/<str:slug>', project_views.mentor_form, name='mentorship_form'),
    path('mentorship_view/<str:slug>', project_views.view_mentorships, name='mentorship_view'),
    path('acceptmentor/<int:mentor_id>', project_views.acceptmentor, name="acceptmentor"),
    path('rejectmentor/<int:mentor_id>', project_views.rejectmentor, name="rejectmentor"),

    path('internship_form/<str:slug>', project_views.intern_form, name='internship_form'),
    path('internship_view/<str:slug>', project_views.view_internships, name='internship_view'),
    path('acceptintern/<int:intern_id>', project_views.acceptintern, name="acceptintern"),
    path('rejectintern/<int:intern_id>', project_views.rejectintern, name="rejectintern"),

    path('collaborator_form/<str:slug>', project_views.colab_form, name='collaborator_form'),
    path('internship_view/<str:slug>', project_views.view_collaborations, name='collaborator_view'),
    path('acceptintern/<int:colab_id>', project_views.acceptcolab, name="acceptcolab"),
    path('rejectintern/<int:colab_id>', project_views.rejectcolab, name="rejectcolab"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdfund/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path

from Accounts import views as account_views
from Projects import views as project_views
from Miscellaneous import views as MiscViews




urlpatterns = [
    path('admin/', admin.site.urls),
#  path('', account_views.LandingPageView.as_view(), name='home'),
    path('', account_views.DashboardView.as_view(), name='home'),
    path('user_accounts/', include('Accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('transactions/', include('transactions.urls')),
    path('projects/', include('Projects.urls')),
    path('<str:username>/<str:slug>/', project_views.ProjectDetailView, name='project_details'),
    path('dashboard/', account_views.DashboardView.as_view(), name='dashboard'),
    path('login/', account_views.LoginFormDef, name='login'),
    path('logout/', account_views.LogoutView, name='logout'),

    path('signup/', account_views.SignupView.as_view(), name='signup'),
    path('signupform/', account_views.signup_form, name='signupform'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            account_views.activate, name='activate'),
    path('browse/', project_views.browse_projects, name='browse_projects'),
    path('misc/', include('Miscellaneous.urls')),

    path('<str:username>/', account_views.UserProfileView, name='user_profile'),


]

Accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from Accounts.forms import ProfileChangeForm, AccountInfoChangeForm, BankDetailsChangeForm
from Accounts.models import CustomUser, Profile, BankDetails, Subsriptions, History
from Miscellaneous.models import FeaturedResearch, UpcomingFeatures, News
from Projects.models import ProjectDetails, Collaborators, Bookmarks, ProjectTags, Interns
from Accounts import forms as account_forms
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth import get_user_model
from django.conf import settings
from django.shortcuts import get_object_or_404
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
import requests

headers = {
    'developer_key': 'becbbce45f79c6f5109f848acd540567',
    'secret-key': 'MC6dKW278tBef+AuqL/5rW2K3WgOegF0ZHLW/FriZQw=',
    'secret-key-timestamp': '1516705204593',
}

User = get_user_model()

# Registration Views:

class SignupView(TemplateView):
    template_name = 'Accounts/signup.html'


def signup_form(request):
    if request.method == 'POST':
        form = account_forms.SignupForm(data=request.POST)
        if form.is_valid():
            if form.cleaned_data['accept_terms'] == 'on':
                user = CustomUser()
                user.username = form.cleaned_data['username']
                user.email = form.cleaned_data['email']
                user.set_password(form.cleaned_data['password'])
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.kyc_done = False
                user.kyc_applied = False
                user.is_active = False
                user.save()
                prof = Profile()
                prof.user = CustomUser.objects.get(username__exact=form.cleaned_data['username'])
                prof.save()
                bank = BankDetails()
                bank.user = CustomUser.objects.get(username__exact=form.cleaned_data['username'])
                bank.save()
                print("user created")
                current_site = get_current_site(request)
                mail_subject = 'Activate your Oversight account'
                body = render_to_string('registration/acc_activate_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                print("body created")


                to_email = form.cleaned_data.get('email')
                message = Mail(
                    from_email="sameeranbandishti93@gmail.com",
                    to_emails=to_email,
                    subject=mail_subject,
                    html_content=body
                )
                try:
                    sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
                    print("API Key Found")
                    response = sg.send(message)
                    print(response.status_code)
                    print(response.body)
                    print(response.headers)
                except Exception as e:
                    print(e.message)

                messages.info(request, "Check inbox and confirm your email to activate your account.")
            else:
                messages.error(request, "Please accept Terms And Conditions to create account.")
            return render(request, 'Accounts/signup.html')

        else:

            temp_list = list(form.errors.values())
            print(temp_list)
            error_list = []
            for er in temp_list:
                error_list.append(er[0])
            print(error_list)
            return render(request, 'Accounts/signup.html', {'errors': error_list})




def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        # return redirect('home')
        messages.info(request, "Welcome To Oversight! We Are Glad To Have You On Board. Your Account Has Been Confirmed")
        return redirect('dashboard')
    else:
        user.delete()
        messages.error(request, "Apologies, There Was An Error With Your Confirmation. Would You Please Give It Another Shot")
        return redirect('signup')



# Login Views:

def LoginFormDef(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('Accounts:dashboard')
            else:
                messages.warning(request, "Your Account Seems To Have Not Been Activated. Please Check Your Mailbox and Activate Your Account")
        else:
            messages.error(request, 'Either Your Username or Password is Incorrect')

    return render(request, 'Accounts/login.html')


def LogoutView(request):
    logout(request)
    messages.info(request,"You Have Been Logged Out")
    return redirect('login')



# Dashboard Related Views:

class DashboardView( LoginRequiredMixin, TemplateView):

    login_url = '/login/'
    redirect_field_name = None

    template_name = 'Dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users_projects = ProjectDetails.objects.filter(user=self.request.user)
        for project in users_projects:
            # project.completion_percentage = (project.balance_amount/project.target_amount)*100.0
            project.completion_percentage = 0
            project.save()

        if users_projects is not None:
            context['Projects'] = users_projects
        user = CustomUser.objects.get(username=self.request.user.username)
        context['user'] = user
        context['FeaturedResearch'] = FeaturedResearch.objects.all()
        context['UpcomingFeatures'] = UpcomingFeatures.objects.all()
        context['News'] = News.objects.all()

        subscribed_to = Subsriptions.objects.filter(Subscriber=user).values_list('Subscribed_To__username',
                                                                                              flat=True)
        events = History.objects.filter(user__username__in=subscribed_to).order_by('time_of_action')

        context['events'] = events

        context['colabs'] = Collaborators.objects.filter(requesting_user=user)

        context['bookmarks'] = Bookmarks.objects.filter(user=user)

        context['Tags'] = ProjectTags.objects.all()

        context['Interns'] = Interns.objects.all()
        context['current_bookmarks'] = Bookmarks.objects.values_list('project_id__project_slug',flat=True).filter(user=user)
        return context


class ProfileAboutView(LoginRequiredMixin, TemplateView):

    login_url = '/login/'
    redirect_field_name = None

    template_name = 'Dashboard/profile-about.html'


class PricingView(LoginRequiredMixin, TemplateView):

    login_url = '/login/'
    redirect_field_name = None

    template_name = 'Dashboard/pricing.html'


class LandingPageView(LoginRequiredMixin, TemplateView):

    login_url = '/login/'
    redirect_field_name = None

    template_name = 'Landing/index.html'

def UserProfileView(request,username):
    try:
        viewed_user = CustomUser.objects.get(username=username)
    except Exception as e:
        return HttpResponse(e)
    try:
        operating_user = CustomUser.objects.get(username=request.user.username)
    except Exception as e:
        operating_user = None
    try:
        subslist = Subsriptions.objects.filter(Subscriber=request.user)
    except Exception as f:
        pass
    subbed = True
    try:
        subslist = subslist.get(Subscribed_To=viewed_user)
    except Exception as e:
        subbed = False
        print(e)
    # if subslist is not None:
    #     subbed = True
    # else:
    #     subbed = False

    projects = ProjectDetails.objects.filter(user=viewed_user)



    return render(request, 'Accounts/profile-new.html', {'viewed_user':viewed_user, 'user':operating_user, 'projects':projects, 'subbed': subbed})

@login_required(login_url='/login/')
def profile_change_form(request):
    viewed_username = request.user.username
    if viewed_username == viewed_username:
        if request.method == 'POST':
            form = ProfileChangeForm(request.POST)
            if form.is_valid():
                user = CustomUser.objects.get(username=viewed_username)
                prof = Profile.objects.get(user=user)
                if form.cleaned_data['designation']: prof.designation = form.cleaned_data['designation']
                if form.cleaned_data['institute']: prof.institute = form.cleaned_data['institute']

templates/Accounts/feed.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Feed</title>
</head>
<body>
<H2>This is Your Feed {{ user.username }}</H2>
<br><br><br><br><br>
{% for event in events %}
    <h4>Username: {{ event.user.username }}</h4>
    <p>Time and Date: {{ event.time_of_action }}</p>
    {% if event.type_of_action == "Creation" %}
    <p>Created a New Project: <a href="{% url 'Projects:project_details' project_id=event.project_id.project_id %}">{{ event.project_id.title }}</a></p>
    {% elif event.type_of_action == "Recom" %}
    <p>A New Recomendation Has Been Added To The Project: <a href="{% url 'Projects:project_details' project_id=event.project_id.project_id %}">{{ event.project_id.title }}</a></p>
    {% endif %}
<br><br>
{% endfor %}

</body>
</html>

templates/Accounts/profile-new.html
<!DOCTYPE html>
{% load staticfiles %}
{% load mathfilters %}

<html lang="en">
<!--[if IE 9 ]><html class="ie9"><![endif]-->

<!-- Mirrored from bootstrapsale.com/projects/maed/v1/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Mar 2019 21:56:20 GMT -->

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ viewed_user.first_name }} {{ viewed_user.last_name }}</title>



  {#    The Files Below This Are A Part Of The Semantics UI Repository #}
  <link href="{% static 'Semantics/css/semantic.css' %}" rel="stylesheet">
  {#    <link href="{% static 'Semantics/css/semantic.min.css' %}" rel="stylesheet"> #}



  <script src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>

  <script src="{% static 'Semantics/js/semantic.js' %}"></script>
  <script src="{% static 'Semantics/js/semantic.min.js' %}"></script>
  <script src="{% static 'Semantics/js/package.js' %}"></script>

  {# The Imports Below are the components  #}

  {#  CSS  #}

  {#  Assets  #}



  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

</head>

<body style="background: #fff !important">

    {% include 'header-internal.html' with usern=user.username %}


  <div class="ui main container" style="padding: 15px 0px 15px 0px;">

      <div class="ui grid">
        
          <div class="twelve wide column">
              <br><br><br><br>
            {% if viewed_user.user_accept_interns %}
              <a class="ui grey label" data-tooltip="Anyone can click here to apply for internship." id="apply_for_internship" ><i class="fas fa-user-graduate">&ensp;</i>Accepting Interns</a>
              {% endif %}
            {% if viewed_user.user_accept_collaborations %}
              <a class="ui grey label" data-tooltip="Anyone can click here to apply for collaboration." id="apply_for_collaboration"><i class="fas fa-users">&ensp;</i>Accepting Collaborations</a>
              {% endif %}
            {% if viewed_user.username == user.username %}
              <a href="{% url 'Accounts:account_settings' %}" class="ui purple label" style="float:right;" data-tooltip="Public visitors don't see this button.">
                <i class="fas fa-edit">&ensp;</i>Edit Profile</a>
          {% endif %}
            

                <script>
                    $(document).ready(function () {
                          $('#apply_for_internship').click(function () {
                            $('#internshipModalDiv')
                                .modal('setting', 'closable', false)
                                .modal('show');
                        });
                        $('#apply_for_collaboration').click(function () {
                            $('#collaborationModalDiv')
                                .modal('setting', 'closable', false)
                                .modal('show');
                        });
                    });
                </script>

                <div class="ui basic modal" id="internshipModalDiv">
                    <div class="header">Apply for Internship</div>
                    <div class="content">
                        <h5>Write your message to {{ user.username }}</h5>
                        <form class="ui form" method="POST" action="#">

                            <textarea rows="4" id="mentorship_body" name="body" class="required"
                                placeholder="Good evening, Mr. Arjun. I've been checking out your project X and would really like to work under you on the same. How about we connect to discuss further? Checkout out the following details."></textarea>
                                <h5>Upload project proposals or any additional files (Optional)</h5>
                                <input type="file" id="file" name="file">
                                <br><br>
                                <input type="file" id="file" name="file">
                              </div>
                    <div class="actions">
                        <button type="submit" class="ui green ok inverted button">Send Proposal</button>
                        <button type="reset" class="ui red basic cancel inverted button">Cancel</button>
                    </div>
                    </form>
                </div>
                <div class="ui basic modal" id="collaborationModalDiv">
                    <div class="header">Apply for Collaboration</div>
                    <div class="content">
                        <h5>Write your message to `user's full name`</h5>
                        <form class="ui form" method="POST" action="#">

                            <textarea rows="4" id="mentorship_body" name="message"
                                placeholder="Hey, Arjun. I've an interesting research project and believe we can collaborate on it. How about we connect to discuss further? Checkout out the following details."></textarea>
                                <h5>Upload project proposals or any additional files (Optional)</h5>
                                <input type="file" id="file" name="file">
                                <br><br>
                                <input type="file" id="file" name="file">
                              </div>
                    <div class="actions">
                        <button type="submit" class="ui green ok inverted button">Send Proposal</button>
                        <button type="reset" class="ui red basic cancel inverted button">Cancel</button>
                    </div>
                    </form>
                </div>


            <h1>{{ viewed_user.first_name }} {{ viewed_user.last_name }}</h1>
           <h3 style="margin-top: 2px; font-family: 'Courier New', Courier, monospace">oversight.in/{{ viewed_user.username }}</h3>
           <br><br>
          <p style="font-size: 16px">{{ viewed_user.profile.bio }}</p>

           <br><br>

           <script language='javascript'>
              $(document).ready(function () {
                $('.ui.accordion').accordion();
              });
            </script>

           <h3>Published Projects</h3>
           <div class="ui inverted segment">
           {% if projects.all %}
              <div class="ui inverted accordion">
                  {% for proj in projects %}
                <div class="title">
                  <i class="dropdown icon"></i>
                  {{ proj.title }}  <a style="float: right; color: white" href="{% url 'project_details' slug=proj.project_slug username=viewed_user.username%}"><i class="fas fa-eye">&ensp;</i>View</a>
                </div>
                <div class="content">
                  <p>{{ proj.description }}</p>
                </div>
                  {% endfor %}
              </div>
           {% else %}
           <p style="color: white">No Projects Found</p>
           {% endif %}
           </div>

            <!--
            <h3>Lectures & Talks</h3>
            <div class="ui inverted segment">
                <div class="ui inverted accordion">
                  <div class="title">
                    <i class="dropdown icon"></i>
                    What is a dog?
                  </div>
                  <div class="content">
                    <p>A dog is a type of domesticated animal. Known for its loyalty and faithfulness, it can be found as a welcome guest in many households across the world.</p>
                  </div>
                  <div class="title">
                    <i class="dropdown icon"></i>
                    What kinds of dogs are there?
                  </div>
                  <div class="content">
                    <p>There are many breeds of dogs. Each breed varies in size and temperament. Owners often select a breed of dog that they find to be compatible with their own lifestyle and desires from a companion.</p>
                  </div>
                  <div class="title">
                    <i class="dropdown icon"></i>
                    How do you acquire a dog?
                  </div>
                  <div class="content">
                    <p>Three common ways for a prospective owner to acquire a dog is from pet shops, private owners, or shelters.</p>
                    <p>A pet shop may be the most convenient way to buy a dog. Buying a dog from a private owner allows you to assess the pedigree and upbringing of your dog before choosing to take it home. Lastly, finding your dog from a shelter, helps give a good home to a dog who may not find one so readily.</p>
                  </div>
                </div>
              </div>
              
              <h3>Selected Publications</h3>
            <div class="ui inverted segment">
                <div class="ui inverted relaxed divided list">
                  <div class="item">
                    <div class="content">
                      <div class="header">Snickerdoodle</div>
                      An excellent companion
                    </div>
                  </div>
                  <div class="item">
                    <div class="content">
                      <div class="header">Poodle</div>
                      A poodle, its pretty basic
                    </div>
                  </div>
                  <div class="item">
                    <div class="content">
                      <div class="header">Paulo</div>
                      He's also a dog
                    </div>
                  </div>
                </div>
              </div>


              <h3>Intellectual Property</h3>
            <div class="ui inverted segment">
                <div class="ui inverted relaxed divided list">
                    {% for proj in projects %}
                        {% if proj.intellectual_property %}
                  <div class="item">
                    <div class="content">
                      <div class="header">{{ proj.intellectual_property }}</div>
                      An excellent companion
                    </div>
                  </div>
                        {% endif %}
                    {% endfor %}
                </div>
              </div>

              -->



          </div>

            <div class="four wide column">
                <br><br><br><br> <br><br>
            {% if user is not None %}
                {% if subbed == False %}
              <a href="{% url 'Accounts:subscribe' viewed_user=user.username %}"
                data-tooltip="Subscribe to {{ user.username }}'s RSS feed." style="font-size: 20px; color: orange"> <i
                    class="fas fa-rss-square"></i></a>
                    {% else %}
                    <a href="{% url 'Accounts:unsubscribe' viewed_user=user.username %}"
                       data-tooltip="Unsubscribe from {{ user.username }}s RSS feed." style="font-size: 20px; color: black"> <i
                    class="fas fa-rss-square"></i></a>
                    {% endif %}

            {% endif %}
            <br><br>
              {% if user.profile.website is not None %}
              <a href="https://{{ user.profile.website }}" class="ui white label" style="font-family: 'Courier New', Courier, monospace"><i class="fas fa-link">&ensp;</i>{{ user.profile.website }}</a>
                <br><br>
                {% endif %}
            {% if user.profile.codebase_handle is not None %}
              <a href="https://{{ user.profile.codebase_handle }}" class="ui black label" style="font-family: 'Courier New', Courier, monospace"><i class="fas fa-code">&ensp;</i>{{ user.profile.codebase_handle }}</a>
              <br><br>
            {% endif %}
            {% if user.profile.linkedin_handle is not None %}
              <a href="https://{{ user.profile.linkedin_handle }}" class="ui blue label"  style="font-family: 'Courier New', Courier, monospace"><i class="fab fa-linkedin-in">&ensp;</i>{{ user.profile.linkedin_handle }}</a>
              <br><br>
            {% endif %}
            {% if user.profile.instagram_handle is not None %}
              <a href="https://{{ user.profile.instagram_handle }}" class="ui pink label"  style="font-family: 'Courier New', Courier, monospace"><i class="fab fa-instagram">&ensp;</i>{{ user.profile.instagram_handle }}</a>
              <br><br>
            {% endif %}
            {% if user.profile.twitter_handle is not None %}
              <a href="https://{{ user.profile.twitter_handle }}" class="ui teal label"  style="font-family: 'Courier New', Courier, monospace"><i class="fab fa-twitter">&ensp;</i>{{ user.profile.twitter_handle }}</a>
            {% endif %}
              <br><br>    
              <br><br>    

              <p style="font-size: 16px"><b>Current Affiliation</b></p>
              <p style="font-size: 16px">{% if viewed_user.profile.designation is not None %}{{ viewed_user.profile.designation }},{% else %}Designation Not Updated,{% endif %}  <i>{% if user.profile.institute is not None %}{{ user.profile.institute }}{% else %}Institute Not Updated{% endif %}</i></p>

              </div>
              
            </div>
          
            <br><br><br><br><br><br>

  </div>
  {% include 'footer-internal.html' %}

</body>
</html>

templates/Accounts/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  <h2>Profile</h2>
  <form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Update Profile</button>
</form>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a> |
  <a href="{% url 'signup' %}">signup</a>
{% endif %}
{% endblock %}